extends Node
class_name WorldGenerator
# WorldGenerator.gd — procedural level generation.

signal room_exit_reached  # Emitted when the player walks through the right doorway
signal enemies_spawned(count: int)  # Emitted after enemies are spawned in a room

# Builds rooms as 2D grids of tile IDs, then instantiates sprites + collision.
# All tile textures are generated by PixelRenderer — no image files used.

# ── Physics layers ────────────────────────────────────────────────────────────
# Layer 1 = room geometry (walls/floors/platforms)
# Layer 2 = enemies (Nullman, RivalBlade)
const LAYER_GEOMETRY := 1
const LAYER_ENEMY    := 2
const LAYER_PLAYER   := 4

# ── Tile ID constants ─────────────────────────────────────────────────────────
const EMPTY      := 0
const FLOOR      := 1
const WALL       := 2
const PLATFORM   := 3
const NULLSTONE  := 4
const CHECKPOINT := 5
const ABYSS      := 6   # Pit — falling in kills
const DOOR       := 7
const PRESSURE_PLATE := 8   # Puzzle trigger tile
const LOCKED_DOOR    := 9   # Puzzle lock tile

const TILE_SIZE  := 16
const ROOM_W     := 44  # Tiles wide
const ROOM_H     := 22  # Tiles tall

# ── Cached textures (generated once, reused for every tile) ──────────────────
var _tex: Dictionary = {}

func _ready() -> void:
	_cache_textures()

func _cache_textures() -> void:
	_tex[FLOOR]      = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.FLOOR,      0)
	_tex[WALL]       = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.WALL,       1)
	_tex[PLATFORM]   = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.PLATFORM,  2)
	_tex[NULLSTONE]  = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.NULLSTONE,  3)
	_tex[CHECKPOINT] = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.CHECKPOINT, 0)
	_tex[DOOR]       = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.DOOR,       7)
	_tex[PRESSURE_PLATE] = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.PRESSURE_PLATE, 8)
	_tex[LOCKED_DOOR]    = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.LOCKED_DOOR, 9)
	_tex[ABYSS]          = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.ABYSS, 10)

# ── Graph-based room generation (new pipeline) ──────────────────────────────
# Generates a tile grid for a single DungeonGraph node using the full
# RoomTerrainGenerator pipeline (archetype skeleton → theme shape →
# portal carving → decoration).
func build_grid_for_graph_node(graph: DungeonGraph, node_id: int, rng: RandomNumberGenerator, theme: int) -> Array:
	return RoomTerrainGenerator.render_room(graph, node_id, rng, theme)



# ── Build room into the scene ─────────────────────────────────────────────────
# parent should be a Node2D in the scene tree (e.g. the "World" node)
# If suppress_triggers is true, does not add the default exit/abyss triggers
# (Game.gd handles them internally when using DungeonPlan).
func build_room(grid: Array, parent: Node2D, suppress_triggers: bool = false) -> void:
	for y in range(grid.size()):
		for x in range(grid[y].size()):
			var id: int = grid[y][x]
			if id == EMPTY or id == ABYSS:
				continue

			var world_x := x * TILE_SIZE
			var world_y := y * TILE_SIZE

			# Visual sprite
			var sprite        := Sprite2D.new()
			sprite.position   = Vector2(world_x + TILE_SIZE * 0.5, world_y + TILE_SIZE * 0.5)
			sprite.texture    = _tex.get(id, _tex[FLOOR])
			parent.add_child(sprite)

			# Collision for solid tiles
			if id in [FLOOR, WALL, PLATFORM, NULLSTONE, CHECKPOINT, LOCKED_DOOR]:
				var body: StaticBody2D
				if id == PLATFORM:
					body = DestructibleTile.new()
					body.linked_sprite = sprite
				else:
					body = StaticBody2D.new()
				var shape := CollisionShape2D.new()
				var rect  := RectangleShape2D.new()
				rect.size          = Vector2(TILE_SIZE, TILE_SIZE)
				shape.shape        = rect
				body.position      = sprite.position
				body.add_child(shape)
				parent.add_child(body)

			# Register checkpoint with GameManager
			if id == CHECKPOINT:
				GameManager.set_checkpoint(Vector2(world_x, world_y - TILE_SIZE))

	if not suppress_triggers:
		_add_exit_trigger(parent)
		_add_abyss_kill_trigger(parent, grid[0].size(), grid.size())

# ── Enemy spawning ───────────────────────────────────────────────────────────
# Spawns enemies based on a room spec dict (precise counts).
func spawn_enemies_from_spec(parent: Node2D, spec: Dictionary) -> void:
	var enemies: Dictionary = spec.get("enemies", {})
	var num_nullman: int = enemies.get("nullman", 0)
	var num_rival: int = enemies.get("rival", 0)
	var has_champion: bool = spec.get("has_champion", false)
	var actual_room_w: int = spec.get("room_w", ROOM_W)
	var actual_room_h: int = spec.get("room_h", ROOM_H)
	var grid: Array = spec.get("grid", [])

	if num_nullman > 0 or num_rival > 0:
		var rng := RandomNumberGenerator.new()
		rng.seed = randi()
		if num_nullman > 0:
			_spawn_nullman(parent, rng, num_nullman, randi(), actual_room_w, actual_room_h, grid)
		if num_rival > 0:
			_spawn_rival(parent, rng, num_rival, randi(), actual_room_w, actual_room_h, grid)

	emit_signal("enemies_spawned", num_nullman + num_rival)

# Scans the grid at tile column tx for the top floor row near expected_row.
# Returns a pixel Y that places the entity 2 rows above the actual floor.
static func _find_enemy_spawn_y(grid: Array, tx: int, expected_row: int, room_h: int) -> float:
	if grid.is_empty() or tx < 0 or tx >= grid[0].size():
		return float((expected_row - 2) * TILE_SIZE)
	# Search ±6 rows around the expected floor row
	for dy in range(-6, 7):
		var fy := expected_row + dy
		if fy < 3 or fy >= room_h - 1:
			continue
		if grid[fy][tx] == FLOOR and grid[fy - 1][tx] != FLOOR:
			# fy is the top floor tile; spawn 2 rows above it
			return float((fy - 2) * TILE_SIZE)
	return float((expected_row - 2) * TILE_SIZE)

func _spawn_nullman(parent: Node2D, rng: RandomNumberGenerator, count: int, seed_val: int, room_w: int = ROOM_W, room_h: int = ROOM_H, grid: Array = []) -> void:
	var floor_y := room_h - 4

	for i in range(count):
		var nullman := CharacterBody2D.new()
		nullman.set_script(load("res://scripts/enemy/Nullman.gd"))
		nullman.collision_layer = LAYER_ENEMY
		nullman.collision_mask = LAYER_GEOMETRY | LAYER_PLAYER

		var spawn_x := rng.randf_range(float(TILE_SIZE) * 4.0, float(room_w - 4) * TILE_SIZE - 40.0)
		var tile_x := clampi(int(spawn_x / float(TILE_SIZE)), 1, room_w - 2)
		var spawn_y := _find_enemy_spawn_y(grid, tile_x, floor_y - 2, room_h)
		nullman.position = Vector2(spawn_x, spawn_y)

		# Add sprite (shard texture generated from room seed for variety)
		var sprite := Sprite2D.new()
		sprite.name = "Sprite"
		sprite.texture = PixelRenderer.generate_enemy_texture(PixelRenderer.EnemyType.NULLMAN, seed_val + i)
		sprite.scale = Vector2(1.5, 1.5)
		sprite.centered = true
		nullman.add_child(sprite)
		nullman.set("sprite", sprite)

		# Add collision
		var cs := CollisionShape2D.new()
		var shape := RectangleShape2D.new()
		shape.size = Vector2(16, 20)
		cs.shape = shape
		nullman.add_child(cs)

		# Damage comes from windup pulse (Nullman.gd), not a hitbox.
		parent.add_child(nullman)

func _spawn_rival(parent: Node2D, rng: RandomNumberGenerator, count: int, seed_val: int, room_w: int = ROOM_W, room_h: int = ROOM_H, grid: Array = []) -> void:
	var floor_y := room_h - 4

	for i in range(count):
		var rival := CharacterBody2D.new()
		rival.set_script(load("res://scripts/enemy/RivalBlade.gd"))
		rival.collision_layer = LAYER_ENEMY
		rival.collision_mask = LAYER_GEOMETRY | LAYER_PLAYER

		var spawn_x := rng.randf_range(float(TILE_SIZE) * 5.0, float(room_w - 6) * TILE_SIZE - 60.0)
		var tile_x := clampi(int(spawn_x / float(TILE_SIZE)), 1, room_w - 2)
		var spawn_y := _find_enemy_spawn_y(grid, tile_x, floor_y - 2, room_h)
		rival.position = Vector2(spawn_x, spawn_y)

		# Add collision (script creates body/blade/hitbox nodes itself)
		var cs := CollisionShape2D.new()
		var shape := RectangleShape2D.new()
		shape.size = Vector2(20, 40)
		cs.shape = shape
		rival.add_child(cs)

		parent.add_child(rival)

# Returns where the player should stand when first entering a room from the left.
# Matches the Y formula used by checkpoints so the player lands on the floor correctly.
# Public wrappers for individual triggers (used when build_room uses suppress_triggers)
func add_abyss_kill_trigger(parent: Node2D) -> void:
	_add_abyss_kill_trigger(parent, ROOM_W, ROOM_H)

func add_abyss_kill_trigger_for_room(parent: Node2D, room_w: int, room_h: int) -> void:
	_add_abyss_kill_trigger(parent, room_w, room_h)

func get_entry_position() -> Vector2:
	var floor_y := ROOM_H - 4
	return Vector2(4 * TILE_SIZE, (floor_y - 2) * TILE_SIZE)

# Spawns an invisible Area2D at the right doorway.
# When the player walks through, room_exit_reached fires once.
func _add_exit_trigger(parent: Node2D) -> void:
	var floor_y  := ROOM_H - 4
	var door_top := floor_y - 5

	var area := Area2D.new()
	area.name        = "RoomExitTrigger"
	area.monitoring  = true
	area.monitorable = false
	area.collision_mask = 4  # Detect player on layer 3

	var cs   := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size  = Vector2(float(TILE_SIZE), float(TILE_SIZE) * 5.0)
	cs.shape   = rect
	area.add_child(cs)

	# Centre the trigger on the doorway opening
	area.position = Vector2(
		float(ROOM_W - 1) * float(TILE_SIZE) + float(TILE_SIZE) * 0.5,
		(float(door_top) + 2.5) * float(TILE_SIZE)
	)

	area.body_entered.connect(func(body: Node2D):
		if body.is_in_group("player"):
			room_exit_reached.emit()
	)

	parent.add_child(area)

# Abyss kill trigger — player dies when falling below the room floor
func _add_abyss_kill_trigger(parent: Node2D, room_w: int, room_h: int) -> void:
	var area := Area2D.new()
	area.name = "AbyssKillTrigger"
	area.monitoring = false  # Armed after a short delay so room-entry teleport can't false-trigger
	area.monitorable = false
	area.collision_mask = 4 | 2  # Layer 3 (player) + layer 2 (enemies)

	var cs := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = Vector2(float(room_w) * float(TILE_SIZE), float(TILE_SIZE) * 2.0)
	cs.shape = rect
	area.add_child(cs)

	var floor_y := room_h - 4
	area.position = Vector2(
		float(room_w) * float(TILE_SIZE) * 0.5,
		float(floor_y + 4) * float(TILE_SIZE)
	)

	area.body_entered.connect(func(body: Node2D):
		print("[KILLZONE] body_entered: %s groups=%s pos=%s vel=%s" % [
			body.name, body.get_groups(),
			body.global_position.round(),
			body.velocity.round() if body is CharacterBody2D else Vector2.ZERO
		])
		if body.is_in_group("player"):
			print("[KILLZONE] → killing player")
			if body.has_method("take_damage"):
				body.take_damage(9999)
		elif body.is_in_group("enemy"):
			print("[KILLZONE] → enemy fell into abyss, queuing free (no essence)")
			body.queue_free()
	)

	parent.add_child(area)

	# Arm the kill zone after 5 physics frames so the player can settle after
	# a room-entry teleport (Phase C can remove floor tiles the bridge doesn't refill).
	var arm_timer := area.get_tree().create_timer(5.0 / 60.0)
	arm_timer.timeout.connect(func(): if is_instance_valid(area): area.monitoring = true)
