extends Node
class_name WorldGenerator
# WorldGenerator.gd — procedural level generation.

signal room_exit_reached  # Emitted when the player walks through the right doorway
signal enemies_spawned(count: int)  # Emitted after enemies are spawned in a room

# Builds rooms as 2D grids of tile IDs, then instantiates sprites + collision.
# All tile textures are generated by PixelRenderer — no image files used.

const _HexBreakableTile = preload("res://scripts/world/HexBreakableTile.gd")

# ── Physics layers ────────────────────────────────────────────────────────────
# Layer 1 = room geometry (walls/floors/platforms)
# Layer 2 = enemies (Nullman, RivalBlade)
const LAYER_GEOMETRY := 1
const LAYER_ENEMY    := 2
const LAYER_PLAYER   := 4

# ── Tile ID constants ─────────────────────────────────────────────────────────
const EMPTY      := 0
const FLOOR      := 1
const WALL       := 2
const PLATFORM   := 3
const NULLSTONE  := 4
const CHECKPOINT := 5
const ABYSS      := 6   # Pit — falling in kills
const DOOR       := 7
const PRESSURE_PLATE := 8   # Puzzle trigger tile
const LOCKED_DOOR    := 9   # Puzzle lock tile
const HEX_WALL       := 10  # Wall that requires a hex ability to destroy

const TILE_SIZE  := 16
const ROOM_W     := 44  # Tiles wide
const ROOM_H     := 22  # Tiles tall

# ── Cached textures (generated once, reused for every tile) ──────────────────
var _tex: Dictionary = {}

# ── Room grid cache — persists generated grids so revisiting a room returns
# the same layout. Keyed by node_id. Cleared on new dungeon start.
var _grid_cache: Dictionary = {}
var _tile_image_cache: Dictionary = {}
var _far_environment: Sprite2D
var _structure_layer: Sprite2D
var _far_base_position := Vector2.ZERO
var _structure_base_position := Vector2.ZERO

const LIGHTING_PROFILES := {
	RegionTheme.HexTheme.GEOCRASH: {"ambient": Color(0.52, 0.40, 0.27), "emitter": Color(1.0, 0.48, 0.16), "falloff": "hex", "flicker": 0.10, "scene": "geocrash"},
	RegionTheme.HexTheme.VOIDREND: {"ambient": Color(0.33, 0.37, 0.50), "emitter": Color(0.24, 0.46, 0.90), "falloff": "void", "flicker": 0.02, "scene": "voidrend"},
	RegionTheme.HexTheme.ECHOSCREAM: {"ambient": Color(0.45, 0.30, 0.33), "emitter": Color(0.95, 0.18, 0.22), "falloff": "hex", "flicker": 0.18, "scene": "echoscream"},
	RegionTheme.HexTheme.MEMOREAVE: {"ambient": Color(0.50, 0.42, 0.34), "emitter": Color(0.92, 0.70, 0.48), "falloff": "harmonic", "flicker": 0.05, "scene": "memoreave"},
	RegionTheme.HexTheme.NULLPULSE: {"ambient": Color(0.34, 0.34, 0.34), "emitter": Color(0.94, 0.12, 0.08), "falloff": "hex", "flicker": 0.15, "scene": "nullpulse"},
	RegionTheme.HexTheme.TECHNOMANTIC: {"ambient": Color(0.42, 0.42, 0.34), "emitter": Color(0.95, 0.48, 0.10), "falloff": "harmonic", "flicker": 0.04, "scene": "technomantic"},
}

func clear_cache() -> void:
	_grid_cache = {}
	_tile_image_cache = {}

func _ready() -> void:
	_cache_textures()

func _process(_delta: float) -> void:
	# Procedural parallax: the environment is a place with depth, not a flat fill.
	var player_node := get_tree().get_first_node_in_group("player") as Node2D
	if player_node == null:
		return
	if is_instance_valid(_far_environment):
		_far_environment.position = _far_base_position + player_node.global_position * 0.08
	if is_instance_valid(_structure_layer):
		_structure_layer.position = _structure_base_position + player_node.global_position * 0.24

func _cache_textures() -> void:
	_tex[FLOOR]      = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.FLOOR,      0)
	_tex[WALL]       = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.WALL,       1)
	_tex[PLATFORM]   = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.PLATFORM,  2)
	_tex[NULLSTONE]  = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.NULLSTONE,  3)
	_tex[CHECKPOINT] = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.CHECKPOINT, 0)
	_tex[DOOR]       = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.DOOR,       7)
	_tex[PRESSURE_PLATE] = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.PRESSURE_PLATE, 8)
	_tex[LOCKED_DOOR]    = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.LOCKED_DOOR, 9)
	_tex[ABYSS]          = PixelRenderer.generate_tile_texture(PixelRenderer.TileType.ABYSS, 10)

# ── Graph-based room generation (new pipeline) ──────────────────────────────
# Generates a tile grid for a single DungeonGraph node using the full
# RoomTerrainGenerator pipeline (archetype skeleton → theme shape →
# portal carving → decoration).
func build_grid_for_graph_node(graph: DungeonGraph, node_id: int, rng: RandomNumberGenerator, theme: int) -> Array:
	if _grid_cache.has(node_id):
		return _grid_cache[node_id].duplicate(true)
	var grid: Array = RoomTerrainGenerator.render_room(graph, node_id, rng, theme)
	_grid_cache[node_id] = grid.duplicate(true)
	return grid



# ── Build room into the scene ─────────────────────────────────────────────────
# parent should be a Node2D in the scene tree (e.g. the "World" node)
# If suppress_triggers is true, does not add the default exit/abyss triggers
# (Game.gd handles them internally when using DungeonPlan).
func build_room(grid: Array, parent: Node2D, suppress_triggers: bool = false, node_id: int = -1) -> void:
	var room_w: int = grid[0].size() if grid.size() > 0 else ROOM_W
	var room_h: int = grid.size()
	for y in range(room_h):
		for x in range(room_w):
			var id: int = grid[y][x]
			if id == EMPTY or id == ABYSS:
				continue

			var world_x := x * TILE_SIZE
			var world_y := y * TILE_SIZE

			# Visual sprite
			var sprite        := Sprite2D.new()
			sprite.position   = Vector2(world_x + TILE_SIZE * 0.5, world_y + TILE_SIZE * 0.5)
			sprite.texture    = _tex.get(id, _tex[FLOOR]) if id != HEX_WALL else _tex[WALL]
			parent.add_child(sprite)
			if id in [FLOOR, WALL, NULLSTONE, HEX_WALL]:
				_add_tile_occluder(sprite)

			# Collision for solid tiles
			if id in [FLOOR, WALL, PLATFORM, NULLSTONE, CHECKPOINT, LOCKED_DOOR, HEX_WALL]:
				var body: StaticBody2D
				if id == PLATFORM:
					var dtile := DestructibleTile.new()
					dtile.linked_sprite = sprite
					body = dtile
					if node_id >= 0:
						var gx := x
						var gy := y
						dtile.destroyed.connect(func():
							if _grid_cache.has(node_id) and gy < _grid_cache[node_id].size() and gx < _grid_cache[node_id][gy].size():
								_grid_cache[node_id][gy][gx] = EMPTY
						)
				elif id == FLOOR or id == HEX_WALL:
					var htile := _HexBreakableTile.new()
					htile.linked_sprite = sprite
					htile.position      = sprite.position
					parent.add_child(htile)
					var type := PixelRenderer.TileType.FLOOR if id == FLOOR else PixelRenderer.TileType.WALL
					var pos_key := Vector2i(x, y)
					var src_img: Image
					if node_id >= 0 and _tile_image_cache.has(node_id) and _tile_image_cache[node_id].has(pos_key):
						src_img = _tile_image_cache[node_id][pos_key]
					else:
						src_img = PixelRenderer.generate_tile_image(
							type,
							hash(pos_key)
						)

					if node_id >= 0:
						var gx := x
						var gy := y
						htile.image_updated.connect(func(img: Image):
							if not _tile_image_cache.has(node_id):
								_tile_image_cache[node_id] = {}
							_tile_image_cache[node_id][pos_key] = img.duplicate()
						)
						htile.destroyed.connect(func():
							if _grid_cache.has(node_id) and gy < _grid_cache[node_id].size() and gx < _grid_cache[node_id][gy].size():
								_grid_cache[node_id][gy][gx] = EMPTY
							if _tile_image_cache.has(node_id):
								_tile_image_cache[node_id].erase(pos_key)
						)

					htile.setup(src_img)
					continue
				else:
					body = StaticBody2D.new()
				var shape := CollisionShape2D.new()
				var rect  := RectangleShape2D.new()
				rect.size          = Vector2(TILE_SIZE, TILE_SIZE)
				shape.shape        = rect
				body.position      = sprite.position
				body.add_child(shape)
				parent.add_child(body)

			# Register checkpoint with GameManager
			if id == CHECKPOINT:
				GameManager.set_checkpoint(Vector2(world_x, world_y - TILE_SIZE))

	if not suppress_triggers:
		_add_exit_trigger(parent, room_w, room_h)
		_add_abyss_kill_trigger(parent, room_w, room_h)

func apply_room_lighting(parent: Node2D, theme: int, seed_val: int, is_sanctuary: bool = false, is_blade_attuned: bool = false, room_w: int = ROOM_W, room_h: int = ROOM_H, archetype: int = 0, complexity: float = 0.5) -> void:
	var profile: Dictionary = LIGHTING_PROFILES.get(theme, LIGHTING_PROFILES[RegionTheme.HexTheme.GEOCRASH])
	var room_size := Vector2i(room_w * TILE_SIZE, room_h * TILE_SIZE)
	var overscan := Vector2i(512, 384)
	var backdrop_size := room_size + overscan * 2
	var far_world := Sprite2D.new()
	far_world.name = "FarEnvironment"
	far_world.texture = PixelRenderer.generate_far_environment_texture(
		backdrop_size.x, backdrop_size.y,
		Color(0.035, 0.045, 0.08) if is_blade_attuned else profile["ambient"].darkened(0.70),
		PixelRenderer.C_CRACK_GLOW if is_blade_attuned else profile["emitter"],
		seed_val, "blade_attuned" if is_blade_attuned else profile["scene"]
	)
	far_world.centered = false
	far_world.position = Vector2(-overscan.x, -overscan.y)
	far_world.z_index = -20
	parent.add_child(far_world)
	_far_environment = far_world
	_far_base_position = far_world.position
	var backdrop := Sprite2D.new()
	backdrop.name = "RoomStructureLayer"
	backdrop.texture = PixelRenderer.generate_atmosphere_texture(
		backdrop_size.x, backdrop_size.y,
		Color.TRANSPARENT,
		PixelRenderer.C_BLADE_BODY if is_blade_attuned else profile["emitter"],
		seed_val,
		archetype,
		complexity
	)
	backdrop.centered = false
	backdrop.position = Vector2(-overscan.x, -overscan.y)
	backdrop.z_index = -12
	parent.add_child(backdrop)
	_structure_layer = backdrop
	_structure_base_position = backdrop.position
	var ambient := CanvasModulate.new()
	ambient.name = "RegionalAmbient"
	# The tutorial is the one location tuned directly to the Blade: void-steel
	# ambient values with violet core emission, rather than a regional Hex palette.
	ambient.color = Color(0.52, 0.52, 0.66) if is_blade_attuned else (Color(0.82, 0.76, 0.64) if is_sanctuary else profile["ambient"])
	parent.add_child(ambient)
	var rng := RandomNumberGenerator.new()
	rng.seed = seed_val
	var emitter_count := 8 if is_blade_attuned else (3 if room_w >= 36 else 2)
	for i in range(emitter_count):
		var light := PointLight2D.new()
		light.name = ("BladeAttunedEmitter" if is_blade_attuned else "BackgroundEmitter") + "_%d" % i
		light.texture = PixelRenderer.generate_light_mask(80 + i * 16, 0.45, "harmonic" if (is_sanctuary or is_blade_attuned) else profile["falloff"])
		light.color = PixelRenderer.C_CRACK_GLOW if is_blade_attuned else (Color(1.0, 0.84, 0.62) if is_sanctuary else profile["emitter"])
		light.energy = 0.82 if is_blade_attuned else (0.42 if is_sanctuary else 0.32)
		light.position = Vector2(rng.randf_range(64.0, float(room_size.x - 64)), rng.randf_range(56.0, float(maxi(80, room_size.y - 120))))
		light.z_index = -10
		light.range_z_min = -20
		light.range_z_max = 10
		light.shadow_enabled = not is_sanctuary and not is_blade_attuned
		parent.add_child(light)
		var source := Sprite2D.new()
		source.name = "EnvironmentalLightSource_%d" % i
		source.texture = PixelRenderer.generate_light_mask(10, 0.75, "harmonic")
		source.modulate = light.color
		source.position = light.position
		source.z_index = -11
		parent.add_child(source)
	if is_blade_attuned:
		var key_light := PointLight2D.new()
		key_light.name = "BladeAttunedKeyLight"
		key_light.texture = PixelRenderer.generate_light_mask(180, 0.55, "harmonic")
		key_light.color = PixelRenderer.C_CRACK_GLOW
		key_light.energy = 0.95
		key_light.position = Vector2(float(room_size.x) * 0.5, float(room_size.y) * 0.36)
		key_light.z_index = -10
		key_light.range_z_min = -20
		key_light.range_z_max = 10
		parent.add_child(key_light)

func _add_tile_occluder(sprite: Sprite2D) -> void:
	var occluder := LightOccluder2D.new()
	var polygon := OccluderPolygon2D.new()
	var half := float(TILE_SIZE) * 0.5
	polygon.polygon = PackedVector2Array([Vector2(-half, -half), Vector2(half, -half), Vector2(half, half), Vector2(-half, half)])
	occluder.occluder = polygon
	sprite.add_child(occluder)

# ── Enemy spawning ───────────────────────────────────────────────────────────
# Spawns enemies based on a room spec dict (precise counts).
func spawn_enemies_from_spec(parent: Node2D, spec: Dictionary) -> void:
	var enemies: Dictionary = spec.get("enemies", {})
	var num_nullman: int = enemies.get("nullman", 0)
	var num_rival: int = enemies.get("rival", 0)
	var has_champion: bool = spec.get("has_champion", false)
	var actual_room_w: int = spec.get("room_w", ROOM_W)
	var actual_room_h: int = spec.get("room_h", ROOM_H)
	var grid: Array = spec.get("grid", [])

	if num_nullman > 0 or num_rival > 0:
		var rng := RandomNumberGenerator.new()
		rng.seed = randi()
		if num_nullman > 0:
			_spawn_nullman(parent, rng, num_nullman, randi(), actual_room_w, actual_room_h, grid)
		if num_rival > 0:
			_spawn_rival(parent, rng, num_rival, randi(), actual_room_w, actual_room_h, grid)

	emit_signal("enemies_spawned", num_nullman + num_rival)

# Scans the grid across tile column tx (and neighboring columns up to ±2) for
# the top floor tile, from bottom to top. Returns a pixel Y that places the
# entity 2 rows above the actual floor. Falls back to expected_row if no floor
# tile is found.
static func _find_enemy_spawn_y(grid: Array, tx: int, expected_row: int, room_h: int) -> float:
	if grid.is_empty() or tx < 0 or tx >= grid[0].size():
		return float((expected_row - 2) * TILE_SIZE)
	var w: int = grid[0].size()
	var x_min := maxi(0, tx - 2)
	var x_max := mini(w - 1, tx + 2)
	# Search from bottom to top for topmost FLOOR
	for fy in range(room_h - 2, 3, -1):
		for fx in range(x_min, x_max + 1):
			if grid[fy][fx] == FLOOR and grid[fy - 1][fx] != FLOOR:
				return float((fy - 2) * TILE_SIZE)
	return float((expected_row - 2) * TILE_SIZE)

func _spawn_nullman(parent: Node2D, rng: RandomNumberGenerator, count: int, seed_val: int, room_w: int = ROOM_W, room_h: int = ROOM_H, grid: Array = []) -> void:
	for i in range(count):
		var nullman := CharacterBody2D.new()
		nullman.set_script(load("res://scripts/enemy/Nullman.gd"))
		nullman.collision_layer = LAYER_ENEMY
		nullman.collision_mask = LAYER_GEOMETRY | LAYER_PLAYER

		var spawn_x := rng.randf_range(float(TILE_SIZE) * 4.0, float(room_w - 4) * TILE_SIZE - 40.0)
		var tile_x := clampi(int(spawn_x / float(TILE_SIZE)), 1, room_w - 2)
		var spawn_y := _find_enemy_spawn_y(grid, tile_x, room_h - 6, room_h)
		nullman.position = Vector2(spawn_x, spawn_y)

		# Add sprite (shard texture generated from room seed for variety)
		var sprite := Sprite2D.new()
		sprite.name = "Sprite"
		sprite.texture = PixelRenderer.generate_enemy_texture(PixelRenderer.EnemyType.NULLMAN, seed_val + i)
		sprite.scale = Vector2(1.5, 1.5)
		sprite.centered = true
		nullman.add_child(sprite)
		nullman.set("sprite", sprite)

		# Add collision
		var cs := CollisionShape2D.new()
		var shape := RectangleShape2D.new()
		shape.size = Vector2(16, 20)
		cs.shape = shape
		nullman.add_child(cs)

		# Damage comes from windup pulse (Nullman.gd), not a hitbox.
		parent.add_child(nullman)

func _spawn_rival(parent: Node2D, rng: RandomNumberGenerator, count: int, seed_val: int, room_w: int = ROOM_W, room_h: int = ROOM_H, grid: Array = []) -> void:
	for i in range(count):
		var rival := CharacterBody2D.new()
		rival.set_script(load("res://scripts/enemy/RivalBlade.gd"))
		rival.collision_layer = LAYER_ENEMY
		rival.collision_mask = LAYER_GEOMETRY | LAYER_PLAYER

		var spawn_x := rng.randf_range(float(TILE_SIZE) * 5.0, float(room_w - 6) * TILE_SIZE - 60.0)
		var tile_x := clampi(int(spawn_x / float(TILE_SIZE)), 1, room_w - 2)
		var spawn_y := _find_enemy_spawn_y(grid, tile_x, room_h - 6, room_h)
		rival.position = Vector2(spawn_x, spawn_y)

		# Add collision (script creates body/blade/hitbox nodes itself)
		var cs := CollisionShape2D.new()
		var shape := RectangleShape2D.new()
		shape.size = Vector2(20, 40)
		cs.shape = shape
		rival.add_child(cs)

		parent.add_child(rival)

# Returns where the player should stand when first entering a room from the left.
# Matches the Y formula used by checkpoints so the player lands on the floor correctly.
# Public wrappers for individual triggers (used when build_room uses suppress_triggers)
func add_abyss_kill_trigger(parent: Node2D) -> void:
	_add_abyss_kill_trigger(parent, ROOM_W, ROOM_H)

func add_abyss_kill_trigger_for_room(parent: Node2D, room_w: int, room_h: int) -> void:
	_add_abyss_kill_trigger(parent, room_w, room_h)

func get_entry_position(room_h: int = ROOM_H) -> Vector2:
	return Vector2(4 * TILE_SIZE, (room_h - 6) * TILE_SIZE)

func _add_exit_trigger(parent: Node2D, room_w: int = ROOM_W, room_h: int = ROOM_H) -> void:
	var door_bottom := maxi(3, room_h - 6)
	var door_top := maxi(2, door_bottom - 5)

	var area := Area2D.new()
	area.name        = "RoomExitTrigger"
	area.monitoring  = true
	area.monitorable = false
	area.collision_mask = 4

	var cs   := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size  = Vector2(float(TILE_SIZE), float(TILE_SIZE) * float(door_bottom - door_top + 1))
	cs.shape   = rect
	area.add_child(cs)

	area.position = Vector2(
		float(room_w - 1) * float(TILE_SIZE) + float(TILE_SIZE) * 0.5,
		float(door_top + door_bottom) * float(TILE_SIZE) * 0.5
	)

	area.body_entered.connect(func(body: Node2D):
		if body.is_in_group("player"):
			room_exit_reached.emit()
	)

	parent.add_child(area)

# Abyss kill trigger — player dies when falling below the room floor
func _add_abyss_kill_trigger(parent: Node2D, room_w: int, room_h: int) -> void:
	var area := Area2D.new()
	area.name = "AbyssKillTrigger"
	area.monitoring = false  # Armed after a short delay so room-entry teleport can't false-trigger
	area.monitorable = false
	area.collision_mask = LAYER_PLAYER | LAYER_ENEMY

	var cs := CollisionShape2D.new()
	var rect := RectangleShape2D.new()
	rect.size = Vector2(float(room_w) * float(TILE_SIZE), float(TILE_SIZE) * 2.0)
	cs.shape = rect
	area.add_child(cs)

	area.position = Vector2(
		float(room_w) * float(TILE_SIZE) * 0.5,
		float(room_h) * float(TILE_SIZE)
	)

	area.body_entered.connect(func(body: Node2D):
		print("[KILLZONE] body_entered: %s groups=%s pos=%s vel=%s" % [
			body.name, body.get_groups(),
			body.global_position.round(),
			body.velocity.round() if body is CharacterBody2D else Vector2.ZERO
		])
		if body.is_in_group("player"):
			if GameManager.is_god_mode:
				print("[KILLZONE] → God Mode active: teleporting player back to checkpoint")
				body.global_position = GameManager.get_respawn_position()
				if body is CharacterBody2D:
					body.velocity = Vector2.ZERO
			else:
				print("[KILLZONE] → killing player")
				if body.has_method("take_damage"):
					body.take_damage(9999)
		elif body.is_in_group("enemy"):
			print("[KILLZONE] → enemy fell into abyss, queuing free (no essence)")
			body.queue_free()
	)

	parent.add_child(area)

	# Arm the kill zone after 5 physics frames so the player can settle after
	# a room-entry teleport (Phase C can remove floor tiles the bridge doesn't refill).
	var arm_timer := area.get_tree().create_timer(5.0 / 60.0)
	arm_timer.timeout.connect(func(): if is_instance_valid(area): area.monitoring = true)
